### ISSUE TITLE
colourpicker error

### ISSUE THREAD

**Issue by jfprieur** [yonicd/ggedit#1]
Hello, I must be doing something silly, trying to install using devtools I get:

ERROR: dependency 'colourpicker' is not available for package 'ggedit'

I have the ggextra package installed, I tried searching for a colourpicker package for R but have not found anything.

**Comment by yonicd** [comment]
here is the homepage of colourpicker for R

https://github.com/daattali/colourpicker

**Comment by jfprieur** [comment]
Thanks for the quick reply, I think the issue I am having is that I use the Microsoft R Open and some of the versions are off (for example colourpicker not available in their CRAN and devtools install complains about htmlwidgets version 0.6 instead of 0.7). Will try later at home with a vanilla R install. Thanks again for the help!

**Comment by yonicd** [comment]
no problem
