### ISSUE TITLE
Work with ' instead of "

### ISSUE THREAD

**Issue by talgalili** [yonicd/ggedit#13]
This way to code in the "View Layer Code" wouldn't need to use:
stat=\"identity\"
instead of just:
stat="identity"

**Comment by yonicd** [comment]
fixed

**Comment by talgalili** [comment]
MUCH better.

**Comment by talgalili** [comment]
Maybe showDefaults should also be a parameter controlled in the shiny app itself (not just in ggedit)?

Also, please move from using T/F to TRUE/FALSE...

**Comment by yonicd** [comment]
it is an option in the module call ?ggEdit

**Comment by talgalili** [comment]
(mmm, it appears I can't reopen the issue...)
