### ISSUE TITLE
dput.ggedit - reproduce the code to create the plot

### ISSUE THREAD

**Issue by talgalili** [yonicd/ggedit#14]
For example. if my first code is:

```r
library(ggplot2)
library(ggedit)
p <- ggplot(mtcars, aes(x = hp, y = wt)) + geom_point() + geom_smooth()
p2 <- ggedit(p)
```

I want to run:

```r
dput.ggedit(p2)
```

And to see the new code I'll need to run in order to reproduce the final output I got to through the ggedit workflow.

For example:

```r
dput.ggedit(p2)
[1] "ggplot(mtcars, aes(x = hp, y = wt)) + geom_point(shape=9,colour='#B03131',size=5) + geom_smooth()"
```

Notice that the code should not include the default parameters (so it is as short as possible). You may also include the full range of parameters and defaults as an option (but the default should be to NOT show them).

**Comment by yonicd** [comment]
did look into it. this is beyond the scope of the package. to do this it would mean to create infrastructure to handle labs(), facet_*(),ggplot(),... things that have nothing to do w aesthetics

**Comment by talgalili** [comment]
Can it work for at least the basic aes available in the layout window?

**Comment by yonicd** [comment]
would it help to make a fn that `paste(list(),sep='+')` all the verbose scripts?

**Comment by talgalili** [comment]
Yes.
And if it could be made possible tonight - that would be great :)
(since I will then get to show it tomorrow)

**Comment by yonicd** [comment]
that would be like broom for ggedit :)

**Comment by talgalili** [comment]
You could call it glance :P

**Comment by yonicd** [comment]
ahavti

**Comment by talgalili** [comment]
It may also be good to have it in the shiny app itself.
So this would only work for the layers? (not the themes/labs?)

**Comment by yonicd** [comment]
layers,themes,scales

**Comment by talgalili** [comment]
(p.s.: I don't think it should be called glance - since glance should be for a row of data.frame. I think it should be dput.ggedit)

**Comment by talgalili** [comment]
Sounds good.

**Comment by yonicd** [comment]
dput isnt s3 method. i'd rather go with print.ggedit or str.ggedit which one is better suited?

```
print(obj)
                                                                                                                                                                                                                          point 
"geom_point(mapping=aes(colour=Species),alpha=1,size=4)+scale_colour_manual(values=c('#632922','#008B45','#6495ED'))+theme(panel.background=element_rect(fill='white'),panel.grid.major=element_line(colour='red',linetype=2))" 
                                                                                                                                                                                                                      pointWrap 
                                                "geom_point(mapping=aes(colour=Species),alpha=1,shape=7,size=6)+scale_colour_manual(values=c('#FA8072','#008B45','#6495ED'))+theme(panel.background=element_rect(fill='blue'))" 
```

**Comment by talgalili** [comment]
print.ggedit would be best then.

**Comment by talgalili** [comment]
But make sure to (maybe?) use
+\n
Instead of just +, so that it wouldn't overflow the console.

**Comment by yonicd** [comment]
done

```
print(obj)

point
geom_point(mapping=aes(colour=Species),alpha=0.5,size=3)+
scale_colour_manual(values=c('#9E4A3F','#008B45','#6495ED'))

pointWrap
geom_point(mapping=aes(colour=Species),size=6)+
theme(panel.background=element_rect(fill='white'))

boxplotWrap
geom_boxplot()

pointLine
geom_point(mapping=aes(shape=Species,colour=Petal.Width),size=6)+geom_line(linetype=2)
```

**Comment by yonicd** [comment]
finally there is [dput.ggedit](https://github.com/metrumresearchgroup/ggedit/blob/master/R/stringify.R)

**Comment by talgalili** [comment]
Cool, I played with the basic output of ggedit, and it seems to work in the simple examples I looked into. :+1:
