### ISSUE TITLE
"View Layer Code" add option to not show default parameters

### ISSUE THREAD

**Issue by talgalili** [yonicd/ggedit#15]
When using ggedit, if I run:

```r
library(ggplot2)
library(ggedit)
p <- ggplot(mtcars, aes(x = hp, y = wt)) + geom_point() + geom_smooth()
p2 <- ggedit(p)
```

It says my original layer call was:
```r
"geom_point(mapping=NULL,na.rm=FALSE,data=NULL,position=\"identity\",stat=\"identity\",show.legend=NA,inherit.aes=TRUE)"
```

This is not true, it was:
```r
"geom_point()"
```

Add the option to omit all the default parameters so that the user can more easily see what was changed (especially in Windows where the code is not colored).

**Comment by yonicd** [comment]
done
