### ISSUE TITLE
Add width/height parameters to ggedit

### ISSUE THREAD

**Issue by talgalili** [yonicd/ggedit#16]
Currently, if I edit a plot I will not know how the new parameters will look like in the place I am likely to display the plot. For example, choosing size=2 or size=5 depends on the width/height of the final graphic device in which I plan to display the figure.
Adding these parameters to ggedit, will make sure that when I edit the plot, I will see it in the editor the way I plan to have it later on.
This can also be a field in the shiny app, and/or a parameter in ggedit itself.

**Comment by yonicd** [comment]
done
