### ISSUE TITLE
Failures when calling ggedit::ggedit() without attaching the package

### ISSUE THREAD

**Issue by krlmlr** [yonicd/ggedit#17]
```
library(ggplot2)
p <- ggplot(mpg) + geom_bar(aes(x = class))
ggedit::ggedit(p)


Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    102: shiny::renderPlot [/tmp/Rtmp2s9CU6/R.INSTALL1b12402fb480/ggedit/R/ggeditGadget.R#219]
     92: <reactive:plotObj>
     81: plotObj
     80: origRenderFunc
     79: output$Plot
      4: shiny::runApp
      3: shiny::runGadget
      2: ggeditGadget [/tmp/Rtmp2s9CU6/R.INSTALL1b12402fb480/ggedit/R/ggeditGadget.R#338]
      1: ggedit::ggedit [/tmp/Rtmp2s9CU6/R.INSTALL1b12402fb480/ggedit/R/ggedit.R#125]

```

**Comment by yonicd** [comment]
it has to have an object to run on `ggedit::ggedit(ggedit::pList[1])`

**Comment by krlmlr** [comment]
Does the documentation need to be adapted then? (I'm using the CRAN version, which is fairly recent, but I still may be missing a change.)

**Comment by yonicd** [comment]
its under heavy revision the last month (generalizing to support ggextensions). 

but the above should be the solution in the cran version

**Comment by yonicd** [comment]
this is the current documentation

https://metrumresearchgroup.github.io/ggedit/console.html

**Comment by krlmlr** [comment]
To recap: How do I need to change my original code:

```r
library(ggplot2)
p <- ggplot(mpg) + geom_bar(aes(x = class))
ggedit::ggedit(p)
```

**Comment by yonicd** [comment]
```r
Depends:
    R (>= 2.3.0),
    ggplot2 (>= 2.2.0),
    shinyBS,
    shiny,
```

```r
library(ggplot2)
library(shinyBS)
p <- ggplot(mpg) + geom_bar(aes(x = class))
ggedit::ggedit(p)
```

**Comment by krlmlr** [comment]
I don't think I should be attaching `shinyBS` just to run your package. Is there a way to avoid this?

**Comment by yonicd** [comment]
i tried moving it now from depends to imports and using importsFrom and it still is being persistent on needing `shinyBS` to be attached. 

I'll look into it a bit more later today. 

thank you for raising the issue.

**Comment by krlmlr** [comment]
Thanks for your very prompt response!

**Comment by yonicd** [comment]
could it be that `shinyBS` needs to load `bootstrap.js` and must be attached to do so?

https://github.com/ebailey78/shinyBS/tree/shinyBS3/inst/www

**Comment by krlmlr** [comment]
But then shinyBS should be able to do so without being attached. If you could pull together a reproducible example that shows how shinyBS fails if it's not attached, best without involving ggedit, this would help shinyBS maintainers to fix the problem.

I assume you're importing shinyBS via `requireNamespace()` or a namespace import?

**Comment by yonicd** [comment]
using `roxygen2` `importFrom shinyBS bsModal`

**Comment by krlmlr** [comment]
Yes, that should be sufficient to properly load it on time.

@ebailey78: Any idea why we are required to *attach* shinyBS to run ggedit?

**Comment by yonicd** [comment]
i added a patch to get around shinyBS not loading. `requireNamespace('shinyBS')` in the ggedit call, so it works now in the dev version. But I would still like to hear ebailey's solution

**Comment by yonicd** [comment]
@jcheng5 maybe you know the answer to this question

**Comment by jcheng5** [comment]
Sorry, I don't. I don't know anything about shinyBS.

**Comment by jcheng5** [comment]
Oh, I do know. This is why: https://github.com/ebailey78/shinyBS/blob/c329f8ce43e44579cafbb16fc3109fb69d403e57/R/misc.R#L1-L6

One easy fix would be to change that from onAttach to onLoad. Possibly a better fix would be to stop using addResourcePath at all, and have the dependency objects point to their locations on disk. I wouldn't rule out there being a good reason why @ebailey78 did it this way, but it doesn't immediately occur to me what it is (less copying?).

**Comment by yonicd** [comment]
btw `shinyAce` also is showing the same problem if you dont manually attach `shinyBS` prior to running a shinyapp

**Comment by yonicd** [comment]
got around the problem in shinyBS by adding onLoad [hooks](https://github.com/metrumresearchgroup/ggedit/blob/master/R/zzz.R)

closing
