### ISSUE TITLE
Error: attempt to select less than one element in OneIndex

### ISSUE THREAD

**Issue by vnijs** [yonicd/ggedit#21]
Great work on ggedit! I was trying to see how I could use it to add and remove layers from a plot but keep getting stuck on this message:

`Error in p$labels[[names(layers[[a.rm]]$mapping)]] <- NULL : 
  attempt to select less than one element in OneIndex`

Suppose I have the plot below. I get new code using the ggedit shiny app (2nd line). Now I have 2 geom_point layers and I want to remove the "old" one using remove_geom but that doesn't work as I expected

```
p <- ggplot(mtcars, aes(x = cyl, y = mpg)) + geom_point()
p <- p + geom_point(shape=8,colour='#000000',size=1.5,fill='#FFFFFF',alpha=1,stroke=4)
p %>% remove_geom("point", 1)
```

By the way, I using the pipe operator in my own code extensively but it does looks inconsistent with the `+` used by ggplot. Is it feasible to add `+` as an operator (and perhaps `-` as well)?

**Comment by yonicd** [comment]
i saw that too last week. looked now and a weird [line](https://github.com/metrumresearchgroup/ggedit/blob/master/R/remove_geom.R#L25) got in there (probably an unintentional copy paste).

before i push the correction out, i was conflicted about the `+/-` operators on remove/rgg because of the indexing needed when there are more than one of the same geom type (as in your example). any suggestions on getting around this?

thanks for opening the issue

**Comment by vnijs** [comment]
Looking forward to trying out the fix! 

I don't know how common it is to have multiple versions of the same geom type in one plot. Perhaps `-` could default to the last version of the specified geom? Then, if the user needs more control they could revert to `%>%` with an index instead? With this default, something like the below would hopefully work:

```
p <- ggplot(mtcars, aes(x = cyl, y = mpg)) + geom_point()
p <- p - geom_remove("point") +
  geom_point(shape=8,colour='#000000',size=1.5,fill='#FFFFFF',alpha=1,stroke=4)
```

Honestly, though, I  don't know enough about the mechanics of `+/-` under-the-hood. Perhaps https://github.com/thomasp85/patchwork by @thomasp85 could provide some inspiration?

**Comment by yonicd** [comment]
https://github.com/metrumresearchgroup/ggedit/commit/35b9bb58c40274fd06df989523a7ae9fa4a71a63

```r
p <- ggplot(mtcars, aes(x = cyl, y = mpg)) + geom_point()
p <- p + geom_point(shape=8,colour='#000000',size=1.5,fill='#FFFFFF',alpha=1,stroke=4)

p - geom_point() #LIFO
p - geom_point() - geom_point()
```

remove layers  across plots in a list

```r
pList <- as.gglist(ggedit::pList[1:3])
pList - geom_boxplot()
pList - geom_boxplot() - geom_point()
```

add layers across plots in a list

```r
pList + geom_hline(aes(yintercept=3),linetype=2)
```

combining

```r
pList - geom_point() + geom_hline(aes(yintercept=3),linetype=2)
```

**Comment by vnijs** [comment]
Wow! That is really nice! Thanks @yonicd
