### ISSUE TITLE
split_chain not found

### ISSUE THREAD

**Issue by reubsjw** [yonicd/ggedit#25]
Hello,
Thank you for creating such a brilliant tool, but unfortunately I haven't been able to use it because it says 
Error in split_chain(match.call(), env = env) : 
  could not find function "split_chain"
every time I start it from commandline or the add-ins menu.

I have ggplot2v3.3.3, Rv.4.0.5 on Mac OS Big Sur 11.2.3. Also in case relevant, magrittr 2.0.1.

I do hope this is still being maintained, it'd be an extraordinarily useful tool if only I can get it working!

Thanks again,
Reubs

**Comment by yonicd** [comment]
Hi. Thanks for the feedback. I believe this error results from the updated magrittr package. I have seen this issue open up in a lot of repositories lately. ggedit doesnt depend directly on magrittr, it just imports the pipe function for convenience. https://github.com/yonicd/ggedit/blob/f7f0d0828bb8a6410ee7391489db5a0aa71d6395/R/utils.R#L1_L3

**Comment by kylebaron** [comment]
The pipe isn't imported properly.
https://github.com/ronkeizer/vpc/pull/68

@reubsjw If you un-install ggedit and the re-install I believe it should work again.

**Comment by yonicd** [comment]
Thanks @kylebaron for the link.

**Comment by reubsjw** [comment]
Amazing, thank you both!!!
