### ISSUE TITLE
Compatibility with ggplot2 3.5.0

### ISSUE THREAD

**Issue by teunbrand** [yonicd/ggedit#27]
Hello there,

We have been preparing a new release of ggplot2 and during a reverse dependency check, and it seemed ggedit's checks failed. I tried to reproduce this locally, and it seems to occur both with the current CRAN version and the upcoming version of ggplot2.

The problem appears to originate in R/clone_facet.R, where it seems that some of the assumptions have become outdated. The new ggplot2 version adds two additional arguments to both `facet_wrap()` and `facet_grid()`.

If you'd like to test yourself against ggplot2's release candidate, you can install it with the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The release of ggplot2 3.5.0 is scheduled for the 12th of February. The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588. We hope to have informed you in a timely manner about upcoming changes.

**Comment by teunbrand** [comment]
This is just a friendly reminder that the release is scheduled soon.

**Comment by yonicd** [comment]
package updated for 3.5.0 ggplot2 release https://github.com/yonicd/ggedit/commit/d8bf8df2b574a864bde78fb62d4662c0cd57ba0f
