### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by TheRealJAnderson** [yonicd/ggedit#4]
I am trying to install this tool and I run into failures to load ggedit.

Can anyone give any advice? I am on the latest version of R and RStudio.

![image](https://cloud.githubusercontent.com/assets/18294291/22039089/764f35e0-dcc3-11e6-9b46-c3c7ce5e8da3.png)

**Comment by yonicd** [comment]
from the error message it looks like httpuv failed to install for some reason, which shiny depends on it. try installing that package before installing shiny and ggedit
