### ISSUE TITLE
Using ggedit inside a typical shiny app?

### ISSUE THREAD

**Issue by rpodcast** [yonicd/ggedit#5]
I'm extremely impressed with `ggedit` and it's already reduced my time in making quality plots with `ggplot2`!  I make quite a few Shiny apps that produce graphics with `ggplot2`, and in the past I would add some custom inputs for details like font size, axis labels, line size, point size, you get the idea.  But it would be very convenient if I could somehow embed `ggedit` inside the app so that they could click a simple action button to invoke the `ggedit` interface, or even just embed the interface inside a `tabPanel` in shiny.  Admittedly I have not tried this out in practice, but I was curious if `ggedit` has a way to do this in a seamless fashion.

**Comment by yonicd** [comment]
Thank you for the kind words. Your request is currently under dev . Our goal is to make a newer version of renderPlot so that the links are part of the UI. 

But until then I can put on the repo the example of using ggedit as part of a shiny app we showed in rstudioconf , it should give you basic tabPabel functionality.

**Comment by yonicd** [comment]
[here](https://github.com/metrumresearchgroup/ggedit/tree/master/shinyapp) is an example of using ggedit in a regular shinyapp. notice that there is a new version of the package needed in order to run the app.

**Comment by rpodcast** [comment]
Thanks for the update!  I'll review the example code and see how to apply it for my apps.

**Comment by yonicd** [comment]
new version of package now has the ability to run ggedit in any typical shinyapp like renderPlot/outputPlot

see [example](https://github.com/metrumresearchgroup/ggedit/blob/master/ggedit/inst/examples/shinyModule.R)

**Comment by rpodcast** [comment]
What a great use of shiny modules!  Now incorporating `ggedit` in my shiny apps just got a lot easier.  I'll put this in action for some apps and highlight my experiences on a future podcast episode 👍
