### ISSUE TITLE
Allow user to specify title, legend, axes, footnote text

### ISSUE THREAD

**Issue by MikeKSmith** [yonicd/ggedit#9]
Thanks for developing ggedit. I wonder if it would be possible to allow users to update / specify title, legend, axes and footnote text with ggedit? That way, the analyst could provide the basic plot object, which can be QCed in advance and "locked down" independently of changes to the surrounding text. I'm thinking of cases where the analyst produces a "quick and dirty" graph for their own use / review, but subsequently the only thing that changes in later revisions for inclusion in reports is the surrounding textual elements and "style" / theme attributes that you have covered already via ggedit.

**Comment by yonicd** [comment]
Hi

Thank you for the suggestion. 

We use ggedit in conjunction with other UI's that make plots to allow for control on both aspects of the workflow.

For the time being we are keeping the scope of ggedit only to edit ready made plots (which can be reactive objects using the shiny module)

**Comment by yonicd** [comment]
you can also have default plot (`p`), use ggedit to get a new plot (`p1`) then append new title `p1+labs(title,x,y)`. that way the QCed plot is maintained, while allow for title editing
